### ISSUE TITLE
There is a problem with the verification mechanism

### ISSUE THREAD

**Issue by Vost02** [troykelly/hassio-addons-letsencrypt-lexicon#42]
When using aliyun, an error message will appear showing a provider error. After some attempts, I noticed that there is an extra space "_aliyun" in front of aliyun in the prompt, which leads to such a problem.

**Comment by troykelly** [comment]
Hi @Vost02 I'm not sure what the issue is - can you please provide the error, and any messages you are seeing?

If there's a code issue, can you tell me which line - eg https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/blob/a284bf85d8161dbb20549203c601e7b20d193aa8/letslexicon/rootfs/usr/bin/certificates#L193

**Comment by troykelly** [comment]
Closing this for now, let me know if you need anything else.
